apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

patches:
  # Scale down to 1 replica in dev
  - target:
      kind: Deployment
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1

  # Use NodePort instead of LoadBalancer in dev
  - target:
      kind: Service
      name: proxy
    patch: |
      - op: replace
        path: /spec/type
        value: NodePort

commonLabels:
  environment: development
